spring:
  config:
    activate:
      on-profile: test
  datasource:
    hikari:
      username: sa
      # jdbc log 설정
#      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#      jdbc-url: jdbc:log4jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
  h2:
    console:
      enabled: true
  sql:
    init:
      schema-locations: classpath:schema-h2.sql
      data-locations: classpath:data-h2.sql
  jpa:
    database: h2
#    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        order_updates: true
        order_inserts: true

# Mybatis Mapper 경로 지정
mybatis:
  mapper-locations: classpath:mapper/*.xml